/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

/**
 *
 * @author dell
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**@
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal(TelaLogin aThis, boolean par) {
        initComponents();
        new TelaLogin().setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BTVeiculo = new javax.swing.JButton();
        BTProdutos = new javax.swing.JButton();
        BTCaixa = new javax.swing.JButton();
        BTFuncionario = new javax.swing.JButton();
        BTOS = new javax.swing.JButton();
        BTOrcamento = new javax.swing.JButton();
        BTUsuarios = new javax.swing.JButton();
        BTCliente = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BTVeiculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/veiculo.png"))); // NOI18N
        BTVeiculo.setText("Veiculo");
        BTVeiculo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BTVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTVeiculoActionPerformed(evt);
            }
        });

        BTProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/produtos.png"))); // NOI18N
        BTProdutos.setText("Produtos");
        BTProdutos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BTProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTProdutosActionPerformed(evt);
            }
        });

        BTCaixa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/caixa.png"))); // NOI18N
        BTCaixa.setText("Caixa");
        BTCaixa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BTCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTCaixaActionPerformed(evt);
            }
        });

        BTFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/funcionario.png"))); // NOI18N
        BTFuncionario.setText("Funcionario");
        BTFuncionario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BTFuncionario.setMargin(new java.awt.Insets(2, 0, 3, 15));
        BTFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTFuncionarioActionPerformed(evt);
            }
        });

        BTOS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OS.png"))); // NOI18N
        BTOS.setText("OS");
        BTOS.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BTOS.setMargin(new java.awt.Insets(2, 0, 3, 14));
        BTOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTOSActionPerformed(evt);
            }
        });

        BTOrcamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Orçamento.png"))); // NOI18N
        BTOrcamento.setText("Orçamentos");
        BTOrcamento.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BTOrcamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTOrcamentoActionPerformed(evt);
            }
        });

        BTUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user.png"))); // NOI18N
        BTUsuarios.setText("Usuarios");
        BTUsuarios.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BTUsuarios.setIconTextGap(0);
        BTUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTUsuariosActionPerformed(evt);
            }
        });

        BTCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cliente.png"))); // NOI18N
        BTCliente.setText("Cliente");
        BTCliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BTCliente.setMargin(new java.awt.Insets(2, 5, 3, 0));
        BTCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTClienteActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/165577.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BTCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(BTFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(BTProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(BTVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(BTOS, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(BTOrcamento, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(BTUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(BTCaixa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTVeiculo)
                    .addComponent(BTOS, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTOrcamento, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTCliente)
                    .addComponent(BTCaixa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTClienteActionPerformed
        new TelaCliente(this, true).setVisible(true);
    }//GEN-LAST:event_BTClienteActionPerformed

    private void BTVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTVeiculoActionPerformed
        
    }//GEN-LAST:event_BTVeiculoActionPerformed

    private void BTProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTProdutosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTProdutosActionPerformed

    private void BTOrcamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTOrcamentoActionPerformed
       
    }//GEN-LAST:event_BTOrcamentoActionPerformed

    private void BTFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTFuncionarioActionPerformed
        // TODO add your handling code here:
        new TelaFuncionario(this,true).setVisible(true);
    }//GEN-LAST:event_BTFuncionarioActionPerformed

    private void BTCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTCaixaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTCaixaActionPerformed

    private void BTUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTUsuariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTUsuariosActionPerformed

    private void BTOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTOSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTOSActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal(this, true).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTCaixa;
    private javax.swing.JButton BTCliente;
    private javax.swing.JButton BTFuncionario;
    private javax.swing.JButton BTOS;
    private javax.swing.JButton BTOrcamento;
    private javax.swing.JButton BTProdutos;
    private javax.swing.JButton BTUsuarios;
    private javax.swing.JButton BTVeiculo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
