/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas.TelaProdutos;

import Banco.BancoJPA;
import Model.Pecas;
import Model.Pecas_;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dell
 */
public class TelaListarProdutos extends javax.swing.JFrame {

    /**
     * Creates new form TelaListarProdutos
     */
    public TelaListarProdutos(TelaProdutos aThis, boolean par) {
        initComponents();
        atualiza();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 357, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 241, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void atualiza() {
       String[] ColumNames = new String[]{"ID", "Referencia", "Descricao", "Marca", "Aplicacao", "ValorCompra", "ValorVenda", "Quantidade"};
        BancoJPA banco = new BancoJPA();
        Pecas c = new Pecas();
        List<Pecas> dados = banco.listar(c);

        Object[][] data = new Object[dados.size()][ColumNames.length];

        for (int i = 0; i < dados.size(); i++) {
            data[i][0] = dados.get(i).getID();
            data[i][1] = dados.get(i).getReferencia();
            data[i][2] = dados.get(i).getDescricao();
            data[i][3] = dados.get(i).getMarca();
            data[i][4] = dados.get(i).getAplicacao();
            data[i][5] = dados.get(i).getValorCompra();
            data[i][6] = dados.get(i).getValorVenda();
            data[i][7] = dados.get(i).getQuantidade();
        }

        DefaultTableModel modelo = new DefaultTableModel(data, ColumNames);
        jTable1.setModel(modelo);
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
