/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas.TelaProdutos;

import Banco.BancoJPA;
import Model.Pecas;
import Telas.MenuPrincipal;
import javax.swing.JOptionPane;

/**
 *
 * @author dell
 */
public class TelaProdutos extends javax.swing.JFrame {

    /**
     * Creates new form TelaProdutos
     */
    public TelaProdutos(MenuPrincipal aThis, boolean par) {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        JLDescricao = new javax.swing.JLabel();
        JLReferencia = new javax.swing.JLabel();
        JLMarca = new javax.swing.JLabel();
        JLAplicacao = new javax.swing.JLabel();
        JLValorC = new javax.swing.JLabel();
        JLValorV = new javax.swing.JLabel();
        JLQuantidade = new javax.swing.JLabel();
        JTDescricao = new javax.swing.JTextField();
        JTReferencia = new javax.swing.JTextField();
        JTMarca = new javax.swing.JTextField();
        JTAplicacao = new javax.swing.JTextField();
        JTValorC = new javax.swing.JTextField();
        JTValorV = new javax.swing.JTextField();
        JTQuantidade = new javax.swing.JTextField();
        BTPesquisar = new javax.swing.JButton();
        BTIncluir = new javax.swing.JButton();
        BTVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JLDescricao.setText("Descrição");

        JLReferencia.setText("COD/ Referencia");

        JLMarca.setText("Marca");

        JLAplicacao.setText("Aplicação");

        JLValorC.setText("Valor de Compra");

        JLValorV.setText("Valor de Venda");

        JLQuantidade.setText("Quantidade");

        BTPesquisar.setText("Pesquisar");
        BTPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTPesquisarActionPerformed(evt);
            }
        });

        BTIncluir.setText("Incluir");
        BTIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTIncluirActionPerformed(evt);
            }
        });

        BTVoltar.setText("Voltar");
        BTVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JLReferencia)
                            .addComponent(JLMarca)
                            .addComponent(JLDescricao)
                            .addComponent(JLAplicacao)
                            .addComponent(JLValorC)
                            .addComponent(JLValorV)
                            .addComponent(JLQuantidade)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(BTIncluir)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                        .addComponent(BTPesquisar)
                        .addGap(54, 54, 54)
                        .addComponent(BTVoltar))
                    .addComponent(JTValorC)
                    .addComponent(JTAplicacao)
                    .addComponent(JTReferencia)
                    .addComponent(JTMarca)
                    .addComponent(JTValorV)
                    .addComponent(JTDescricao)
                    .addComponent(JTQuantidade))
                .addGap(0, 0, 0))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLDescricao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTReferencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLReferencia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLMarca))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTAplicacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLAplicacao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTValorC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLValorC))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTValorV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLValorV))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLQuantidade))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTIncluir)
                    .addComponent(BTPesquisar)
                    .addComponent(BTVoltar))
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTPesquisarActionPerformed
        new TelaListarProdutos(this,true).setVisible(true);
    }//GEN-LAST:event_BTPesquisarActionPerformed

    private void BTVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTVoltarActionPerformed
      dispose();
    }//GEN-LAST:event_BTVoltarActionPerformed

    
    private void clear() {
        JTDescricao.setText("");
        JTReferencia.setText("");
        JTMarca.setText("");
        JTAplicacao.setText("");
        JTValorC.setText("");
        JTValorV.setText("");
        JTQuantidade.setText("");
    }
    private void BTIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTIncluirActionPerformed
            if(evt.getSource().equals(BTIncluir)){
                Pecas produto = new Pecas();
                produto.setDescricao(JTDescricao.getText());
                produto.setReferencia(JTReferencia.getText());
                produto.setMarca(JTMarca.getText());
                produto.setAplicacao(JTAplicacao.getText());
                produto.setValorCompra(Double.valueOf(JTValorC.getText()));
                produto.setValorVenda(Double.valueOf(JTValorV.getText()));
                produto.setQuantidade(Integer.valueOf(JTQuantidade.getText()));
                BancoJPA banco = new BancoJPA();
                banco.inserir(produto);
                clear();
                JOptionPane.showMessageDialog(rootPane, "Produto Adcionado");
            }
    }//GEN-LAST:event_BTIncluirActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTIncluir;
    private javax.swing.JButton BTPesquisar;
    private javax.swing.JButton BTVoltar;
    private javax.swing.JLabel JLAplicacao;
    private javax.swing.JLabel JLDescricao;
    private javax.swing.JLabel JLMarca;
    private javax.swing.JLabel JLQuantidade;
    private javax.swing.JLabel JLReferencia;
    private javax.swing.JLabel JLValorC;
    private javax.swing.JLabel JLValorV;
    private javax.swing.JTextField JTAplicacao;
    private javax.swing.JTextField JTDescricao;
    private javax.swing.JTextField JTMarca;
    private javax.swing.JTextField JTQuantidade;
    private javax.swing.JTextField JTReferencia;
    private javax.swing.JTextField JTValorC;
    private javax.swing.JTextField JTValorV;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
