/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas.Veiculos;

import Banco.BancoJPA;
import Model.Veiculo;
import Telas.MenuPrincipal;
import javax.swing.JOptionPane;

/**
 *
 * @author dell
 */
public class TelaVeiculo extends javax.swing.JFrame {

    /**
     * Creates new form TelaVeiculo
     */
    public TelaVeiculo(MenuPrincipal aThis, boolean par) {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JLModelo = new javax.swing.JLabel();
        JTModelo = new javax.swing.JTextField();
        JLMarca = new javax.swing.JLabel();
        JTMarca = new javax.swing.JTextField();
        JLAno = new javax.swing.JLabel();
        JTAno = new javax.swing.JTextField();
        JLCor = new javax.swing.JLabel();
        JTCor = new javax.swing.JTextField();
        JLPlaca = new javax.swing.JLabel();
        JTPlaca = new javax.swing.JTextField();
        JLKM = new javax.swing.JLabel();
        JTKm = new javax.swing.JTextField();
        BTIncluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JLModelo.setText("Modelo");

        JLMarca.setText("Marca");

        JLAno.setText("Ano");

        JLCor.setText("Cor");

        JLPlaca.setText("Placa");

        JLKM.setText("KM");

        BTIncluir.setText("Incluir");
        BTIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTIncluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BTIncluir)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JLModelo)
                            .addComponent(JLMarca)
                            .addComponent(JLAno)
                            .addComponent(JLCor)
                            .addComponent(JLPlaca)
                            .addComponent(JLKM))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JTKm)
                            .addComponent(JTPlaca)
                            .addComponent(JTCor)
                            .addComponent(JTAno)
                            .addComponent(JTMarca)
                            .addComponent(JTModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLModelo)
                    .addComponent(JTModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLMarca)
                    .addComponent(JTMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLAno)
                    .addComponent(JTAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLCor)
                    .addComponent(JTCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLPlaca)
                    .addComponent(JTPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLKM)
                    .addComponent(JTKm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(BTIncluir)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clear() {
        JTModelo.setText("");
        JTMarca.setText("");
        JTCor.setText("");
        JTPlaca.setText("");
        JTAno.setText("");
        JTKm.setText("");
    }
    private void BTIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTIncluirActionPerformed
        if(evt.getSource().equals(BTIncluir)){
            Veiculo veiculo = new Veiculo();
            veiculo.setModelo(JTModelo.getText());
            veiculo.setMarca(JTMarca.getText());
            veiculo.setCor(JTCor.getText());
            veiculo.setAno(JTAno.getText());
            veiculo.setPlaca(JTPlaca.getText());
            veiculo.setKM(Integer.valueOf(JTKm.getText()));
                
                BancoJPA banco = new BancoJPA();
                banco.inserir(veiculo);
                clear();
                JOptionPane.showMessageDialog(rootPane, "Produto Adcionado");
            }
    }//GEN-LAST:event_BTIncluirActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTIncluir;
    private javax.swing.JLabel JLAno;
    private javax.swing.JLabel JLCor;
    private javax.swing.JLabel JLKM;
    private javax.swing.JLabel JLMarca;
    private javax.swing.JLabel JLModelo;
    private javax.swing.JLabel JLPlaca;
    private javax.swing.JTextField JTAno;
    private javax.swing.JTextField JTCor;
    private javax.swing.JTextField JTKm;
    private javax.swing.JTextField JTMarca;
    private javax.swing.JTextField JTModelo;
    private javax.swing.JTextField JTPlaca;
    // End of variables declaration//GEN-END:variables
}
